function fig = ena()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load ena

scrsz = get(groot,'ScreenSize');
scrwd = scrsz(4)/1.5;
scrhg = scrsz(3)/2;
h0 = figure('Units','points', ...
	'CloseRequestFcn','Close', ...
	'Color',[0.87843137254902 0.874509803921569 0.8901960784313731], ...
	'Colormap',mat0, ...
	'FileName','ena.m', ...
	'Name','Efficiency Network Analyser by Fabio Manganiello / some patches applied by Kleber Cardoso', ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[1 scrwd scrhg scrwd], ...
	'ResizeFcn','legend(''ResizeLegend'')', ...
	'Tag','Fig1', ...
	'ToolBar','none');
h1 = uipanel('Title','Data input ',...
     'BackgroundColor','white',...
	 'FontWeight','bold', ...
     'Position',[.01 .61 .24 .38]);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[.13 .88 .055 .025], ...
	'String','2', ...
	'Style','edit', ...
	'Tag','K', ...
	'Visible','off'); % remember changing to 'off'
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.19 .875 .055 .025], ...
	'String','K', ...
	'Style','text', ...
	'Tag','Text K', ...
	'Visible','off'); % remember changing to 'off'
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[.13 .88 .055 .025], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','Ack', ...
	'Visible','off'); % remember changing to 'off'
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.19 .875 .055 .025], ...
	'String','L_a [bit]', ...
	'Style','text', ...
	'Tag','Text Ack', ...
	'Visible','off'); % remember changing to 'off'
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Callback','Prob', ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[.13 .88 .055 .025], ...
	'String','10e-4', ...
	'Style','edit', ...
	'Tag','Prob', ...
	'Visible','off'); % remember changing to 'off'
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.19 .875 .055 .025], ...
	'String','P', ...
	'Style','text', ...
	'Tag','Text P', ...
	'Visible','off'); % remember changing to 'off'
 h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Callback','Lambda', ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[.13 .88 .055 .025], ...
	'String','2', ...
	'Style','edit', ...
	'Tag','Lambda', ...
	'Visible','off'); % remember changing to 'off'
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.19 .875 .055 .025], ...
	'String','Lambda', ...
	'Style','text', ...
	'Tag','Text Lambda', ...
	'Visible','off'); % remember changing to 'off'
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Callback',mat2, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[.13 .92 .055 .025], ...
	'String','100', ...
	'Style','edit', ...
	'Tag','Nodi', ...
	'Visible','off'); % remember changing to 'off'
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.19 .915 .055 .025], ...
	'String','N', ...
	'Style','text', ...
	'Tag','Text N', ...
	'Visible','off'); % remember changing to 'off'
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[.13 .92 .055 .025], ...
	'String','64', ...
	'Style','edit', ...
	'Tag','Win', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.19 .915 .055 .025], ...
	'String','W', ...
	'Style','text', ...
	'Tag','Text W', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[.13 .92 .055 .025], ...
	'String','2', ...
	'Style','edit', ...
	'Tag','Var B', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.19 .915 .055 .025], ...
	'String','B', ...
	'Style','text', ...
	'Tag','Text B', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Callback','TauController', ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[.02 .88 .055 .025], ...
	'String','5', ...
	'Style','edit', ...
	'Tag','Tau', ...
	'Visible','off'); % remember changing to 'off'
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.078 .875 .05 .025], ...
	'String','tau [ms]', ...
	'Style','text', ...
	'Tag','Text tau', ...
	'Visible','off'); % remember changing to 'off'
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[.02 .88 .055 .025], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','Gamma', ...
	'UserData','[ ]', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'Callback',mat6, ...
	'ListboxTop',0, ...
	'Position',[.078 .875 .05 .025], ...
	'String','g', ...
	'Style','text', ...
	'Tag','Text Gamma', ...
	'UserData','[ ]', ...
	'Value',1, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Callback','FreqCifra', ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[.13 .84 .055 .025], ...
	'String','64', ...
	'Style','edit', ...
	'Tag','FreqCifra', ...
	'Visible','off'); % remember changing to 'off'
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.19 .835 .055 .025], ...
	'String','C [kbps]', ...
	'Style','text', ...
	'Tag','Text C', ...
	'Visible','off'); % remember changing to 'off'
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Callback','LengthFrame', ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[.13 .8 .055 .025], ...
	'String','256', ...
	'Style','edit', ...
	'Tag','LengthFrame', ...
	'Visible','off'); % remember changing to 'off'
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.19 .795 .055 .025], ...
	'String','L [bit]', ...
	'Style','text', ...
	'Tag','Text L', ...
	'Visible','off'); % remember changing to 'off'
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontWeight','bold', ...
	'ForegroundColor',[0 0.501960784313725 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.025 .72 .15 .055], ...
	'Style','text', ...
	'Tag','Edit');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.501960784313725 0.501960784313725 0.501960784313725], ...
	'Callback','Plotter', ...
	'ForegroundColor','white', ...
	'ListboxTop',0, ...
	'Position',[.18 .72 .05 .03], ...
	'String','Plot', ...
	'Tag','Plot graph');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ForegroundColor',[0.501960784313725 0.501960784313725 0.501960784313725], ...
	'ListboxTop',0, ...
	'Position',[.02 .7 .22 .001], ...
	'Style','frame', ...
	'Tag','Frame8');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.02 .67 .08 .025], ...
	'String','Coordinates', ...
	'Style','text', ...
	'Tag','StaticText11');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Callback','CoordEnable', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.11 .67 .13 .025], ...
	'String','Enable coordinates', ...
	'Style','checkbox', ...
	'Tag','CoordEnable');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Enable','off', ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[.02 .64 .08 .025], ...
	'Style','edit', ...
	'Tag','xCoord');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.105 .635 .02 .025], ...
	'String','X', ...
	'Style','text', ...
	'Tag','StaticText9');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Enable','off', ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[.14 .64 .08 .025], ...
	'Style','edit', ...
	'Tag','yCoord');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.225 .635 .02 .025], ...
	'String','Y', ...
	'Style','text', ...
	'Tag','StaticText10');

h1 = uipanel('Title','Draw options ',...
     'BackgroundColor',[1 1 1],...
	 'FontWeight','bold', ...
     'Position',[.01 .3 .24 .3]);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'ListboxTop',0, ...
	'Position',[.12 .545 .02 .025], ...
	'String','Min', ...
	'Style','text', ...
	'Tag','StaticText13');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'ListboxTop',0, ...
	'Position',[.19 .545 .02 .025], ...
	'String','Max', ...
	'Style','text', ...
	'Tag','StaticText12');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.02 .52 .055 .025], ...
	'String','X range:', ...
	'Style','text', ...
	'Tag','StaticText16');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'ListboxTop',0, ...
	'Position',[.137 .52 .02 .02], ...
	'String','0', ...
	'Style','text', ...
	'Tag','StaticText14');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Callback','xMax', ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[.17 .52 .055 .025], ...
	'String','1000', ...
	'Style','edit', ...
	'Tag','xMax');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.02 .49 .055 .025], ...
	'String','Y range:', ...
	'Style','text', ...
	'Tag','StaticText17');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Callback','yMin', ...
	'Enable','off', ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[.1 .49 .055 .025], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','yMin');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Callback','yMax', ...
	'Enable','off', ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[.17 .49 .055 .025], ...
	'String','10', ...
	'Style','edit', ...
	'Tag','yMax');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Callback','RangeEnable', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.02 .46 .12 .025], ...
	'String','Enable Y range', ...
	'Style','checkbox', ...
	'Tag','xyEnable');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.02 .43 .055 .025], ...
	'String','Step:', ...
	'Style','text', ...
	'Tag','StaticText15');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Callback','StepControl', ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[.10 .435 .055 .025], ...
	'String','100', ...
	'Style','edit', ...
	'Tag','Step');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Callback','RadioButtonControlL', ...
	'ListboxTop',0, ...
	'Position',[.02 .4 .055 .025], ...
	'String','Linear', ...
	'Style','radiobutton', ...
	'Tag','Linear');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Callback','RadioButtonControlX', ...
	'ListboxTop',0, ...
	'Position',[.08 .4 .08 .025], ...
	'String','Semilog X', ...
	'Style','radiobutton', ...
	'Tag','LogX', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Callback','RadioButtonControlY', ...
	'ListboxTop',0, ...
	'Position',[.16 .4 .08 .025], ...
	'String','Semilog Y', ...
	'Style','radiobutton', ...
	'Tag','LogY');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Callback','RadioButtonControlXY', ...
	'ListboxTop',0, ...
	'Position',[.02 .365 .1 .025], ...
	'String','Log X Log Y', ...
	'Style','radiobutton', ...
	'Tag','LogXLogY');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.16 .365 .08 .025], ...
	'String','Hold on', ...
	'Style','checkbox', ...
	'Tag','holdon');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'ListboxTop',0, ...
	'Position',[.02 .325 .08 .025], ...
	'String','Text on', ...
	'Style','checkbox', ...
	'Tag','Text on');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.1 .325 .08 .025], ...
	'String','Grid', ...
	'Style','checkbox', ...
	'Tag','Grid', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.501960784313725 0.501960784313725 0.501960784313725], ...
	'Callback','FigClear', ...
	'ForegroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.18 .32 .05 .03], ...
	'String','Clear', ...
	'Tag','FigClear');

h1 = uipanel('Title','Data output ',...
     'BackgroundColor','white',...
	 'FontWeight','bold', ...
     'Position',[.01 .01 .24 .28]);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.02 .225 .02 .025], ...
	'String','S=', ...
	'Style','text', ...
	'Tag','StaticText26');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.04 .23 .06 .025], ...
	'Style','edit', ...
	'Tag','Utilizzazione');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.11 .225 .02 .025], ...
	'String','Ao=', ...
	'Style','text', ...
	'Tag','StaticText');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.135 .23 .075 .025], ...
	'Style','edit', ...
	'Tag','Aofferto');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.215 .225 .02 .025], ...
	'String','b/s', ...
	'Style','text', ...
	'Tag','StaticText28');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.02 .19 .02 .025], ...
	'String','a=', ...
	'Style','text', ...
	'Tag','StaticText27');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.04 .191 .06 .025], ...
	'Style','edit', ...
	'Tag','aCoef');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.11 .19 .02 .025], ...
	'String','As=', ...
	'Style','text', ...
	'Tag','StaticText29');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.135 .191 .075 .025], ...
	'Style','edit', ...
	'Tag','Asmaltito');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.215 .19 .02 .025], ...
	'String','b/s', ...
	'Style','text', ...
	'Tag','StaticText30');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.11 .15 .02 .025], ...
	'String','T=', ...
	'Style','text', ...
	'Tag','StaticText31');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.135 .151 .075 .025], ...
	'Style','edit', ...
	'Tag','Tframe');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.215 .15 .02 .025], ...
	'String','ms', ...
	'Style','text', ...
	'Tag','StaticText32');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'ListboxTop',0, ...
	'Position',[.04 .105 .06 .025], ...
	'String','Coordinates', ...
	'Style','text', ...
	'Tag','StaticText20');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.02 .07 .02 .025], ...
	'String','X1=', ...
	'Style','text', ...
	'Tag','StaticText19');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','inactive', ...
	'ForegroundColor',[1 0.501960784313725 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.045 .071 .078 .025], ...
	'Style','edit', ...
	'Tag','xRes');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.135 .07 .02 .025], ...
	'String','X2=', ...
	'Style','text', ...
	'Tag','StaticText42');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'Enable','inactive', ...
	'ForegroundColor',[1 0.501960784313725 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.16 .071 .078 .025], ...
	'Style','edit', ...
	'Tag','x2Res');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.026 .025 .02 .025], ...
	'String','Y=', ...
	'Style','text', ...
	'Tag','StaticText18');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.045 .026 .078 .025], ...
	'Style','edit', ...
	'Tag','yRes');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.501960784313725 0.501960784313725 0.501960784313725], ...
	'Callback','ClearData', ...
	'ForegroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.135 .025 .05 .03], ...
	'String','Clear', ...
	'Tag','ClearData');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.501960784313725 0.501960784313725 0.501960784313725], ...
	'Callback','CalcData01', ...
	'ForegroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.19 .025 .045 .03], ...
	'String','Calc', ...
	'Tag','CalcData');
%%% hide some 'Data output' (what for?)
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.02 .15 .21 .11], ...
	'Style','frame', ...
	'Tag','MascheraOut');

h1 = uipanel('Title','Set TDM-FDM ',...
     'BackgroundColor','white',...
	 'FontWeight','bold', ...
     'Position',[.26 .84 .20 .15]);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor','white', ...
	'ListboxTop',0, ...
	'Position',[.275 .92 .08 .025], ...
	'String','Normalize', ...
	'Style','checkbox', ...
	'Tag','Normal', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0 0], ...
	'Callback','Radio_Contr', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.375 .92 .07 .03], ...
	'String','Controller', ...
	'Tag','Radio_Controller');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.275 .87 .04 .025], ...
	'String','D = f(S)', ...
	'Style','text', ...
	'Tag','StaticText22');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0.501960784313725 1], ...
	'Callback','Radio_TDM', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.34 .87 .045 .03], ...
	'String','TDM', ...
	'Tag','Radio_DTDM');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 0 0], ...
	'Callback','Radio_FDM', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.4 .87 .045 .03], ...
	'String','FDM', ...
	'Tag','Radio_DFDM');

h1 = uipanel('Title','',...
     'BackgroundColor','white',...
     'Position',[.47 .84 .30 .15]);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.48 .95 .06 .025], ...
	'String','Set CSMA', ...
	'Style','text', ...
	'Tag','StaticText37');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontName','Curier', ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[.56 .95 .05 .025], ...
	'String','_ _ _', ...
	'Style','text', ...
	'Tag','StaticText44');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontName','Curier', ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[.625 .95 .06 .025], ...
	'String','_ . _ . _', ...
	'Style','text', ...
	'Tag','StaticText45');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontName','Curier', ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[.7 .95 .05 .025], ...
	'String','. . . .', ...
	'Style','text', ...
	'Tag','StaticText46');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0.501960784313725 1], ...
	'Callback','Radio_CSMAsnp', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.48 .92 .07 .03], ...
	'String','S.non-pers', ...
	'Tag','Pushbutton2');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0.501960784313725 1], ...
	'Callback','Radio_CSMAs1p', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.555 .92 .065 .03], ...
	'String','S.1-pers', ...
	'Tag','Pushbutton3');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0.501960784313725 1], ...
	'Callback','Radio_CSMAnp', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.625 .92 .065 .03], ...
	'String','Non-pers', ...
	'Tag','Pushbutton4');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0.501960784313725 1], ...
	'Callback','Radio_CSMA1p', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.695 .92 .06 .03], ...
	'String','1-pers', ...
	'Tag','Pushbutton5');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.48 .885 .08 .025], ...
	'String','Set CSMA/CD', ...
	'Style','text', ...
	'Tag','StaticText43');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 0 0], ...
	'Callback','Radio_CSMACDsnp', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.48 .86 .07 .03], ...
	'String','S.non-pers', ...
	'Tag','Pushbutton6');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 0 0], ...
	'Callback','Radio_CSMACDs1p', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.555 .86 .065 .03], ...
	'String','S.1-pers', ...
	'Tag','Pushbutton7');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 0 0], ...
	'Callback','Radio_CSMACDnp', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.625 .86 .065 .03], ...
	'String','Non-pers', ...
	'Tag','Pushbutton8');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','RadioButtonCSMAs', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.695 .885 .065 .03], ...
	'String','S = f(G)', ...
	'Style','radiobutton', ...
	'Tag','RadioS', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','RadioButtonCSMAn', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.695 .855 .06 .03], ...
	'String','n = f(a)', ...
	'Style','radiobutton', ...
	'Tag','RadioN');

h1 = uipanel('Title','Save options ',...
     'BackgroundColor','white',...
	 'FontWeight','bold', ...
     'Position',[.78 .84 .21 .15]);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','RadioButtonSaveJ', ...
	'ListboxTop',0, ...
	'Position',[.82 .93 .06 .03], ...
	'String','JPEG', ...
	'Style','radiobutton', ...
	'Tag','RadioJPG', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','RadioButtonSaveT', ...
	'ListboxTop',0, ...
	'Position',[.9 .93 .06 .03], ...
	'String','TIFF', ...
	'Style','radiobutton', ...
	'Tag','RadioTIFF');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','RadioButtonSavePS', ...
	'ListboxTop',0, ...
	'Position',[.82 .895 .06 .03], ...
	'String','EPS', ...
	'Style','radiobutton', ...
	'Tag','RadioPS');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','RadioButtonSaveP', ...
	'ListboxTop',0, ...
	'Position',[.9 .895 .06 .03], ...
	'String','PNG', ...
	'Style','radiobutton', ...
	'Tag','RadioPNG');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.501960784313725 0.501960784313725 0.501960784313725], ...
	'Callback','Salva', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.86 .855 .05 .03], ...
	'String','Save', ...
	'Tag','Salva');

h1 = uipanel('Title','Set Aloha ',...
     'BackgroundColor','white',...
	 'FontWeight','bold', ...
     'Position',[.26 .68 .20 .15]);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','RadioButtonAlohaSG', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.28 .78 .08 .025], ...
	'String','S = f(G)', ...
	'Style','radiobutton', ...
	'Tag','AlohaSG', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','RadioButtonAlohaDG', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.36 .78 .08 .025], ...
	'String','D* = f(G)', ...
	'Style','radiobutton', ...
	'Tag','AlohaDG');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','RadioButtonAlohaDS', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.28 .74 .08 .025], ...
	'String','D* = f(S)', ...
	'Style','radiobutton', ...
	'Tag','AlohaDS');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','RadioButtonAlohaNA', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.36 .74 .08 .025], ...
	'String','n = f(a)', ...
	'Style','radiobutton', ...
	'Tag','AlohaNA');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0.501960784313725 1], ...
	'Callback','Radio_Aloha', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.29 .7 .06 .03], ...
	'String','Aloha', ...
	'Tag','Aloha');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 0 0], ...
	'Callback','Radio_SAloha', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.37 .7 .06 .03], ...
	'String','S.Aloha', ...
	'Tag','SlottedAloha');

h1 = uipanel('Title','Set ARQ ',...
     'BackgroundColor','white',...
	 'FontWeight','bold', ...
     'Position',[.47 .68 .25 .15]);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.485 .765 .1 .025], ...
	'String','W >= 1 + 2a', ...
	'Style','text', ...
	'Tag','StaticText4');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ForegroundColor',[0.501960784313725 0.501960784313725 0.501960784313725], ...
	'ListboxTop',0, ...
	'Position',[.593 .73 .001 .065], ...
	'Style','frame', ...
	'Tag','Frame7');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.61 .765 .08 .025], ...
	'String','W < 1 + 2a', ...
	'Style','text', ...
	'Tag','StaticText5');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0.501960784313725 1], ...
	'Callback','Radio_GoBackNc', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.485 .735 .045 .03], ...
	'String','G.B.N.', ...
	'Tag','GoBackNc');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 0 0], ...
	'Callback','Radio_SRc', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.54 .735 .045 .03], ...
	'String','S.R.', ...
	'Tag','SRc');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0.501960784313725 1], ...
	'Callback','Radio_GoBackN', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.6 .735 .045 .03], ...
	'String','G.B.N.', ...
	'Tag','GoBackN');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 0 0], ...
	'Callback','Radio_SR', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.655 .735 .045 .03], ...
	'String','S.R.', ...
	'Tag','SR');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0 0], ...
	'Callback','Radio_SW', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.485 .695 .045 .03], ...
	'String','S.W.', ...
	'Tag','Stop&Wait');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','RadioButtonARQNA', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.55 .695 .065 .025], ...
	'String','n = f(a)', ...
	'Style','radiobutton', ...
	'Tag','ARQNA', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','RadioButtonARQNL', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.62 .695 .065 .025], ...
	'String','n = f(L)', ...
	'Style','radiobutton', ...
	'Tag','ARQNL');

h1 = uipanel('Title','Token ',...
     'BackgroundColor','white',...
     'FontWeight','bold', ...
     'Position',[.73 .68 .26 .15]);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontName','Curier', ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[.807 .78 .1 .025], ...
	'String','_ _ _', ...
	'Style','text', ...
	'Tag','StaticText44');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontName','Curier', ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[.886 .78 .1 .025], ...
	'String','. . . .', ...
	'Style','text', ...
	'Tag','StaticText46');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0 0], ...
	'Callback','Radio_MT', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.75 .75 .055 .03], ...
	'String','M.T.', ...
	'Tag','mtoken');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0 0], ...
	'Callback','Radio_ST', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.83 .75 .055 .03], ...
	'String','S.T.', ...
	'Tag','stoken');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0 0], ...
	'Callback','Radio_SP', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.91 .75 .055 .03], ...
	'String','S.P.', ...
	'Tag','spacket');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','RadioButtonTokenNA', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.745 .71 .07 .025], ...
	'String','n = f(a)', ...
	'Style','radiobutton', ...
	'Tag','TokenNA', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','RadioButtonTokenNN', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.82 .71 .07 .025], ...
	'String','n = f(N)', ...
	'Style','radiobutton', ...
	'Tag','TokenNN');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','RadioButtonTokenDS', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[.9 .71 .07 .025], ...
	'String','D* = f(S)', ...
	'Style','radiobutton', ...
	'Tag','TokenDS');

h1 = axes('Parent',h0, ...
	'Units','normalized', ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat4, ...
	'Position',[.32 .08 .66 .55], ...
	'Tag','Axes1', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.4989858012170385 -0.07079646017699104 9.160254037844386], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.05882352941176472 0.4955752212389382 9.160254037844386], ...
	'Rotation',90, ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.6166328600405679 1.766961651917404 9.160254037844386], ...
	'Tag','Axes1Text2', ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat5, ...
	'Tag','Axes1Text1', ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.501960784313725 0.501960784313725 0.501960784313725], ...
	'Callback',mat3, ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[.93 .02 .05 .03], ...
	'String','Close', ...
	'Tag','Close');

%%% it seems useless
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[81 369 60 15], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','a', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[144 369 10.5 13.5], ...
	'String','a', ...
	'Style','text', ...
	'Tag','Text a', ...
	'Visible','off');

%%% used internally, not presented in the screen
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[19.5 363.75 45 15], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','Appoggio', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[27.75 379.5 45 15], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','Graph', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[514.5 394.5 45 15], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','VarSalva', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[465.75 420 45 15], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','FunctionCSMA', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[223.5 330.75 45 15], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','PAloha', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[350.25 321.75 45 15], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','Parq', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[537.75 325.5 45 15], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','PToken', ...
	'Visible','off');
% a sort of pop-up screens over the whole app
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ForegroundColor',[0.501960784313725 0.501960784313725 0.501960784313725], ...
	'ListboxTop',0, ...
	'Position',[6.75 7.5 598 485], ...
	'Style','frame', ...
	'Tag','MascheraStampa', ...
	'UserData','[ ]', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontName','Curier', ...
	'FontSize',25, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[268.5 261.75 89.25 30], ...
	'String','Print ...', ...
	'Style','text', ...
	'Tag','Text Print', ...
	'Visible','off');
if nargout > 0, fig = h0; end
